### ISSUE TITLE
Submit to NonGNU ELPA

### ISSUE THREAD

**Issue by bbatsov** [bbatsov/adoc-mode#11]
This will make it easier for Emacs users to discover the package.

**Comment by tarsius** [comment]
I've updated the Melpa recipe to the new location of this package.

We leave it to the maintainer to decide whether to leave the package on Melpa, but usually we prefer to remove it from there once it is available from [Non]GNU Elpa.

**Comment by bbatsov** [comment]
Thanks!

A lot of people still don't know about NonGNU ELPA and it's enabled only since 28.1 out of the box, so I prefer to keep my packages on MELPA for now. But I definitely plan to get adoc-mode to NGE at some point.

**Comment by bbatsov** [comment]
Now that the dependency to `markup-faces` has been eliminated it's probably time to add `adoc-mode` to NonGNU ELPA.

**Comment by bbatsov** [comment]
Anyone can send the necessary patch to emacs-devel. If there are no volunteers I'll do it at some point.
