### ISSUE TITLE
adoc-mode-map uses several variables before they are defined

### ISSUE THREAD

**Issue by ambihelical** [bbatsov/adoc-mode#16]
Updated from the package today, found that adoc-mode-map uses at least one thing before they are defined, and starting adoc-mode gives the following error:

`File mode specification error: (void-variable adoc-help-constrained-quotes) [2 times]`

Moving the define of `adoc-mode-map` just above `(define-derived-mode ...` does the job, but there may be better ways.

**Comment by bbatsov** [comment]
Sorry about this. I'll fix it later today.
