### ISSUE TITLE
Replace obsolete markup-faces to adoc-faces

### ISSUE THREAD

**Issue by dunmaksim** [bbatsov/adoc-mode#25]
Package `markup-faces` is obsolete (latest update 8 years ago). Main idea -- customization font faces for `adoc-mode` like faces for `markdown-mode`: https://github.com/jrblevin/markdown-mode/blob/master/markdown-mode.el#L1827

**Comment by bbatsov** [comment]
I agree this would be better. It's not a lot of work, as the old `adoc-mode` faces are still in the code as obsolete variables (they were made obsolete when the `markup-faces` packages was created), so it's just a matter of swapping them for the faces coming from `markup-faces`. PR welcome!

**Comment by bbatsov** [comment]
See https://github.com/bbatsov/adoc-mode/blob/master/adoc-mode.el#L269 for details.
