### ISSUE TITLE
Flyspell generates overlays for links and alike

### ISSUE THREAD

**Issue by TobiasZawada** [bbatsov/adoc-mode#49]
## Expected behavior

Links like `image:ImageDir/myLovelyCat.png[]` are not checked by Flyspell

## Actual behavior

Currently, Flyspell puts overlays on links which are spelled erroneous.

## Steps to reproduce the problem

Try the following Adoc:

````
== Title

Links like image:ImageDir/myLovelyCat.png[] are not checked by Flyspell
````

### Adoc-Mode version information

```
adoc-mode, version 0.8.0-snapshot
```

### Emacs version

GNU Emacs 29.1 (build 1, x86_64-pc-linux-gnu, GTK+ Version 3.24.33, cairo version 1.16.0) of 2023-08-02, modified by Debian

**Comment by bbatsov** [comment]
This approach might be relevant https://emacs.stackexchange.com/questions/5415/how-can-i-make-flyspell-ignore-urls

**Comment by TobiasZawada** [comment]
> This approach might be relevant https://emacs.stackexchange.com/questions/5415/how-can-i-make-flyspell-ignore-urls

I know the `flyspell-mode-predicate` property of major mode symbols and I have already a branch for it.
My first approach was to let font-lock mark the relevant spots with an `adoc-flycheck-ignore` text property  and only test for this property in the predicate function. With other words: re-use all the hard work that font-lock already does anyway.

**Comment by TobiasZawada** [comment]
@bbatsov Before I create a pull request for this issue I would like to merge [!48](https://github.com/bbatsov/adoc-mode/pull/48).
